# Generated by Django 5.1.3 on 2024-11-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lost',
        ),
        migrations.RemoveField(
            model_name='user',
            name='transfer',
        ),
    ]
