# Generated by Django 5.1.3 on 2024-11-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_country_remove_user_currency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Persone',
        ),
        migrations.AlterModelOptions(
            name='persone',
            options={'verbose_name': 'Persone', 'verbose_name_plural': 'Personens'},
        ),
    ]
