# Generated by Django 5.1.3 on 2024-11-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_user_persone_alter_persone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='phone',
            field=models.CharField(max_length=52, verbose_name='Your Phone'),
        ),
    ]
