# Generated by Django 5.1.3 on 2024-11-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_persone_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Your name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('phone', models.CharField(max_length=52, verbose_name='Your Phone')),
                ('story', models.TextField(verbose_name='Tell your story')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
