# Generated by Django 5.1.3 on 2024-11-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='email',
            new_name='email_c',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='name',
            new_name='name_c',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='phone',
            new_name='phone_c',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='story',
            new_name='story_c',
        ),
        migrations.RenameField(
            model_name='persone',
            old_name='company',
            new_name='company_p',
        ),
        migrations.RenameField(
            model_name='persone',
            old_name='date',
            new_name='date_p',
        ),
        migrations.RenameField(
            model_name='persone',
            old_name='email',
            new_name='email_p',
        ),
        migrations.RenameField(
            model_name='persone',
            old_name='name',
            new_name='name_p',
        ),
        migrations.RenameField(
            model_name='persone',
            old_name='phone',
            new_name='phone_p',
        ),
        migrations.RenameField(
            model_name='persone',
            old_name='story',
            new_name='story_p',
        ),
    ]
