# Generated by Django 5.1.3 on 2024-11-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_email_contacts_email_c_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='email_c',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='name_c',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='phone_c',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='story_c',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='persone',
            old_name='company_p',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='persone',
            old_name='date_p',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='persone',
            old_name='email_p',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='persone',
            old_name='name_p',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='persone',
            old_name='phone_p',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='persone',
            old_name='story_p',
            new_name='story',
        ),
    ]
