# Generated by Django 5.1.3 on 2024-11-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_email_c_contacts_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Last transaction date'),
        ),
    ]
