# Generated by Django 5.1.3 on 2024-11-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_persone_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='phone',
            field=models.IntegerField(max_length=52, verbose_name='Your Phone'),
        ),
    ]
