# Generated by Django 5.1.3 on 2024-11-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_persone_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Your Phone'),
        ),
    ]
